CREATE  TABLE `fantasy_commander`.`fangraphs_batter_standard` (
  `player_id` INT NOT NULL ,
  `name` VARCHAR(45) NULL ,
  `pos` VARCHAR(10) NULL ,
  `dob` VARCHAR(10) NULL ,
  `current_team` VARCHAR(45) NULL ,
  `year` VARCHAR(45) NOT NULL ,
  `team` VARCHAR(45) NOT NULL ,
  `g` INT(4) NULL ,
  `pa` INT(5) NULL ,
  `hr` INT(4) NULL ,
  `r` INT(4) NULL ,
  `rbi` INT(4) NULL ,
  `sb` INT(4) NULL ,
  `bb_pct` VARCHAR(6) NULL ,
  `k_pct` VARCHAR(6) NULL ,
  `iso` DECIMAL(1,3) NULL ,
  `babip` DECIMAL(1,3) NULL ,
  `avg` DECIMAL(1,3) NULL ,
  `obp` DECIMAL(1,3) NULL ,
  `slg` DECIMAL(1,3) NULL ,
  `woba` DECIMAL(1,3) NULL ,
  `wrc_plus` INT(4) NULL ,
  `bsr` DECIMAL(3,1) NULL ,
  `off` DECIMAL(3,1) NULL ,
  `def` DECIMAL(3,1) NULL ,
  `war` DECIMAL(3,1) NULL ,
  PRIMARY KEY (`player_id`, `year`, `team`) );